version: '3.8'

services:
  springboot-app:
    build: ./fournisseurIdentiteApi
    container_name: springboot_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fournisseurapi
      SPRING_DATASOURCE_USERNAME: fournisseurapi
      SPRING_DATASOURCE_PASSWORD: fournisseurapi
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: ["sh", "-c", "until nc -z -v -w30 db 5432; do echo 'Waiting for database...'; sleep 1; done; java -jar /app/app.jar"]
  
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: fournisseurapi
      POSTGRES_USER: fournisseurapi
      POSTGRES_PASSWORD: fournisseurapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d 
 laravel-app:
    build:
      context: ./cloudS5-cryptomonaie
    container_name: laravel_app
    environment:
      DB_CONNECTION: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: fournisseurapi
      DB_USERNAME: fournisseurapi
      DB_PASSWORD: fournisseurapi
    ports:
      - "8000:80"  # Laravel sera disponible sur http://localhost:8000
    depends_on:
      - postgres
    volumes:
      - ./cloudS5-cryptomonaie:/var/www/html
    networks:
      - backend_network


  postgres-laravel:
    image: postgres:15
    container_name: postgres_laravel_container
    environment:
      POSTGRES_DB: cryptomonnaie_db  # Base de données pour Laravel
      POSTGRES_USER: laraveluser  # Utilisateur pour Laravel
      POSTGRES_PASSWORD: laravelpassword  # Mot de passe pour Laravel
    ports:
      - "5434:5432"  # Port 5434 pour Laravel
    volumes:
      - postgres_laravel_data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d

  # Service Nginx pour Laravel
  nginx:
    image: nginx:1.23
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./cloudS5-cryptomonaie:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-app
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local